### PR TITLE
Cleanup instructors

### PR DESCRIPTION
**Pull request by PatrickStevens**
- Did a bunch of stuff
- Did some other stuff
- Even more stuff

You can drag screen shots into here from the desktop, if you wanted

### CODE REVIEW

**Comment by PatrickStevens** [comment]
@deelesh @rkrabill @rgarrity

**Comment by PatrickStevens** [comment]
:dart:  Emoji test

**Comment by robe5395gh** [comment]
:facepunch:

**Comment by rkrabill** [comment]
please keep me updated on your updates to the readme files...
@rgarrity
@deelesh

**Comment by rkrabill** [comment]
:8ball:

**Comment by rkrabill** [comment]
Way to go :+1:

**Comment by PatrickStevens** [comment]
:bow:

**Comment by rkrabill** [comment]
Long live Patrick!

**Comment by rkrabill** [comment]
Hello again, my name is still Rich.  Here is a turtle: :turtle: 

I find it very interesting that Patrick can edit Rich's comments, and there is no record that Patrick was the one doing the editing.  I think it is ok, though, because Patrick is an amazing person.

**Comment by ghost** [comment]
I don't know who you are but I get all your updates about the readme file! WTF is going on? I have literally nothing to do with you guys!

**Comment by robe5395gh** [comment]
What was the last change you received?

**Comment by PatrickStevens** [comment]
Sorry, @PStevens.  People are using the incorrect name.  It should be @patrickstevens

**Pull request merged**
